service: sessy

image: your-registry/sessy

servers:
  web:
    hosts:
      - YOUR_SERVER_IP

registry:
  server: your-registry.example.com
  username: your-username
  password:
    - KAMAL_REGISTRY_PASSWORD

env:
  clear:
    RAILS_LOG_TO_STDOUT: true
    SOLID_QUEUE_IN_PUMA: true
  secret:
    - RAILS_MASTER_KEY
    - DATABASE_URL
    - HTTP_AUTH_USERNAME
    - HTTP_AUTH_PASSWORD

builder:
  args:
    RUBY_VERSION: <%= File.read(".ruby-version").strip.delete_prefix("ruby-") %>
    RAILS_ENV: production
  arch: amd64

asset_path: /rails/public/assets

proxy:
  hosts:
    - sessy.example.com

aliases:
  console: app exec --interactive --reuse "bin/rails console"
  shell: app exec --interactive --reuse "bash"
  logs: app logs -f
  dbc: app exec --interactive --reuse "bin/rails dbconsole"
